// Curated subset of common disposable email domains.
// Source for fuller list: https://github.com/disposable/disposable-email-domains (MIT, regularly updated).
// Update this list periodically; for v3.2 launch an embedded subset is sufficient.
export const DISPOSABLE_DOMAINS: ReadonlySet<string> = new Set([
  "mailinator.com",
  "tempmail.com",
  "guerrillamail.com",
  "guerrillamail.net",
  "guerrillamail.org",
  "trashmail.com",
  "throwawaymail.com",
  "yopmail.com",
  "10minutemail.com",
  "10minutemail.net",
  "maildrop.cc",
  "fakeinbox.com",
  "tempinbox.com",
  "getairmail.com",
  "dispostable.com",
  "sharklasers.com",
  "mailcatch.com",
  "spam4.me",
  "mintemail.com",
  "mohmal.com",
  "tempr.email",
  "armyspy.com",
  "cuvox.de",
  "dayrep.com",
  "einrot.com",
  "fleckens.hu",
  "gustr.com",
  "jourrapide.com",
  "rhyta.com",
  "superrito.com",
  "teleworm.us",
]);
