use keyring::Entry;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use tauri::{AppHandle, Emitter, Manager, Runtime, State};
use tracing::{info, warn};

use crate::state::AppState;

// ── Constants ────────────────────────────────────────────────────────────────

const KEYRING_SERVICE: &str = "voice-tool-v3";
const KEYRING_ACCOUNT_REFRESH_TOKEN: &str = "refresh_token";
const KEYRING_ACCOUNT_DEVICE_ID: &str = "device_fingerprint";

// ── Structs ──────────────────────────────────────────────────────────────────

/// In-memory auth state: pending OAuth nonces, memory-fallback token, keyring flag.
pub struct AuthState {
    /// Nonces generated by `generate_oauth_state` that have not yet been consumed.
    pub pending_oauth_states: Vec<String>,
    /// Memory fallback when the OS keyring is unavailable.
    pub memory_fallback_refresh_token: Option<String>,
    /// Whether the OS keyring was reachable on the last write attempt.
    pub keyring_available: bool,
}

impl AuthState {
    pub fn new() -> Self {
        AuthState {
            pending_oauth_states: Vec::new(),
            memory_fallback_refresh_token: None,
            keyring_available: true,
        }
    }
}

/// Serialisable status returned to the frontend after keyring operations.
#[derive(Debug, Serialize, Deserialize)]
pub struct KeyringStatus {
    pub available: bool,
    pub message: String,
}

// ── Private keyring helpers ───────────────────────────────────────────────────

fn write_keyring(account: &str, value: &str) -> Result<(), String> {
    let entry = Entry::new(KEYRING_SERVICE, account).map_err(|e| e.to_string())?;
    entry.set_password(value).map_err(|e| e.to_string())
}

fn read_keyring(account: &str) -> Result<Option<String>, String> {
    let entry = Entry::new(KEYRING_SERVICE, account).map_err(|e| e.to_string())?;
    match entry.get_password() {
        Ok(val) => Ok(Some(val)),
        Err(keyring::Error::NoEntry) => Ok(None),
        Err(e) => Err(e.to_string()),
    }
}

fn delete_keyring(account: &str) -> Result<(), String> {
    let entry = Entry::new(KEYRING_SERVICE, account).map_err(|e| e.to_string())?;
    match entry.delete_credential() {
        Ok(()) => Ok(()),
        Err(keyring::Error::NoEntry) => Ok(()), // idempotent: already absent
        Err(e) => Err(e.to_string()),
    }
}

// ── Private nonce helper (for deep-link handler, Task 9) ─────────────────────

/// Removes `nonce` from the pending list if present and returns `true`.
/// Returns `false` if the nonce was not found (already consumed or never issued).
/// NOT exposed as a Tauri command — called from Rust's deep-link handler only.
pub fn consume_nonce_from_state<R: Runtime>(app: &AppHandle<R>, nonce: &str) -> bool {
    let state = app.state::<AppState>();
    let mut auth = state.auth.lock().unwrap();
    if let Some(pos) = auth.pending_oauth_states.iter().position(|n| n == nonce) {
        auth.pending_oauth_states.remove(pos);
        info!("OAuth nonce consumed");
        true
    } else {
        warn!("OAuth nonce not found or already consumed");
        false
    }
}

// ── Deep-link validation ──────────────────────────────────────────────────────

/// Payload emitted to the frontend on "auth-deep-link-received".
#[derive(Serialize, Clone)]
pub struct DeepLinkPayload {
    pub url: String,
    pub params: HashMap<String, String>,
    pub valid: bool,
    pub reason: Option<String>,
}

const WHITELIST_TYPES: &[&str] = &["magiclink", "oauth", "signup", "recovery", "email_change"];

/// Entry point called from lib.rs deep-link handlers.
/// NEVER logs the token — only the validity flag + reason.
pub fn emit_deep_link_event<R: Runtime>(app: &AppHandle<R>, url: &str) {
    let payload = parse_and_validate_deep_link(url, app);
    info!(valid = payload.valid, reason = ?payload.reason, "deep link received");
    if let Err(e) = app.emit("auth-deep-link-received", &payload) {
        warn!("failed to emit auth-deep-link-received: {}", e);
    }
}

/// Parse URL, run pure-shape validation, THEN validate OAuth nonce with app state.
fn parse_and_validate_deep_link<R: Runtime>(url: &str, app: &AppHandle<R>) -> DeepLinkPayload {
    match validate_url_shape(url) {
        Err(reason) => invalid(url, reason),
        Ok(params) => {
            // OAuth only: also validate and consume the state nonce.
            if params.get("type").map(|s| s.as_str()) == Some("oauth") {
                match params.get("state") {
                    None => return invalid(url, "missing state for oauth"),
                    Some(nonce) => {
                        if !consume_nonce_from_state(app, nonce) {
                            return invalid(url, "unknown or replayed state nonce");
                        }
                    }
                }
            }
            DeepLinkPayload {
                url: url.to_string(),
                params,
                valid: true,
                reason: None,
            }
        }
    }
}

/// Pure function — no app state needed, fully testable.
/// Validates scheme, host, path, type whitelist, and JWT field shapes.
fn validate_url_shape(url: &str) -> Result<HashMap<String, String>, &'static str> {
    let parsed = url::Url::parse(url).map_err(|_| "malformed url")?;
    if parsed.scheme() != "voice-tool" {
        return Err("wrong scheme");
    }
    if parsed.host_str() != Some("auth") || parsed.path() != "/callback" {
        return Err("wrong host/path");
    }
    let params: HashMap<String, String> = parsed.query_pairs().into_owned().collect();
    let type_val = params.get("type").ok_or("missing type")?;
    if !WHITELIST_TYPES.contains(&type_val.as_str()) {
        return Err("type not whitelisted");
    }
    // Shape-check only: fields that should be JWTs (3 dot-separated parts).
    for field in &["access_token", "refresh_token", "token"] {
        if let Some(v) = params.get(*field) {
            if !looks_like_jwt(v) {
                return Err("jwt field has wrong shape");
            }
        }
    }
    Ok(params)
}

fn invalid(url: &str, reason: &'static str) -> DeepLinkPayload {
    DeepLinkPayload {
        url: url.to_string(),
        params: HashMap::new(),
        valid: false,
        reason: Some(reason.to_string()),
    }
}

fn looks_like_jwt(s: &str) -> bool {
    s.split('.').count() == 3 && s.len() > 20
}

// ── Tauri commands ────────────────────────────────────────────────────────────

/// Write a refresh token to the OS keyring.
/// On keyring failure, stores in memory and returns a degraded `KeyringStatus`.
#[tauri::command]
pub fn store_refresh_token(
    token: String,
    state: State<'_, AppState>,
) -> Result<KeyringStatus, String> {
    let mut auth = state.auth.lock().unwrap();

    match write_keyring(KEYRING_ACCOUNT_REFRESH_TOKEN, &token) {
        Ok(()) => {
            auth.keyring_available = true;
            // Clear the memory fallback — keyring is authoritative.
            auth.memory_fallback_refresh_token = None;
            info!("refresh_token stored in OS keyring");
            Ok(KeyringStatus {
                available: true,
                message: "stored".to_string(),
            })
        }
        Err(e) => {
            warn!("Keyring write failed, falling back to memory: {}", e);
            auth.keyring_available = false;
            auth.memory_fallback_refresh_token = Some(token);
            Ok(KeyringStatus {
                available: false,
                message: format!("Keyring unavailable: {}", e),
            })
        }
    }
}

/// Read the refresh token from the OS keyring (with memory fallback).
#[tauri::command]
pub fn get_refresh_token(state: State<'_, AppState>) -> Result<Option<String>, String> {
    let auth = state.auth.lock().unwrap();

    match read_keyring(KEYRING_ACCOUNT_REFRESH_TOKEN) {
        Ok(Some(token)) => {
            info!("refresh_token read from OS keyring");
            Ok(Some(token))
        }
        Ok(None) => {
            // Keyring has no entry; return memory fallback (may also be None).
            Ok(auth.memory_fallback_refresh_token.clone())
        }
        Err(e) => {
            warn!("Keyring read failed, returning memory fallback: {}", e);
            Ok(auth.memory_fallback_refresh_token.clone())
        }
    }
}

/// Delete the refresh token from the OS keyring and clear the memory fallback.
#[tauri::command]
pub fn clear_refresh_token(state: State<'_, AppState>) -> Result<(), String> {
    let mut auth = state.auth.lock().unwrap();
    auth.memory_fallback_refresh_token = None;
    delete_keyring(KEYRING_ACCOUNT_REFRESH_TOKEN)?;
    info!("refresh_token cleared");
    Ok(())
}

/// Return the device UUID from the OS keyring, generating and persisting a new one if absent.
#[tauri::command]
pub fn get_or_create_device_id() -> Result<String, String> {
    // Try to read existing device ID.
    match read_keyring(KEYRING_ACCOUNT_DEVICE_ID) {
        Ok(Some(id)) => {
            info!("device_id read from OS keyring");
            return Ok(id);
        }
        Ok(None) => {}
        Err(e) => {
            warn!("Keyring read for device_id failed: {}", e);
        }
    }

    // Generate a new UUID v4.
    let new_id = uuid::Uuid::new_v4().to_string();

    // Best-effort persist — ignore write failures.
    if let Err(e) = write_keyring(KEYRING_ACCOUNT_DEVICE_ID, &new_id) {
        warn!("Could not persist device_id to keyring: {}", e);
    } else {
        info!("new device_id generated and stored in OS keyring");
    }

    Ok(new_id)
}

/// Generate a UUID v4 OAuth state nonce and add it to the pending list.
/// The Vec is capped at 16 entries; the oldest 8 are drained when over capacity.
#[tauri::command]
pub fn generate_oauth_state(state: State<'_, AppState>) -> Result<String, String> {
    let mut auth = state.auth.lock().unwrap();

    let nonce = uuid::Uuid::new_v4().to_string();
    auth.pending_oauth_states.push(nonce.clone());

    // Cap at 16 — drain oldest 8 to avoid unbounded growth.
    if auth.pending_oauth_states.len() > 16 {
        auth.pending_oauth_states.drain(0..8);
        warn!("pending_oauth_states exceeded 16 entries; oldest 8 drained");
    }

    info!("OAuth state nonce generated");
    Ok(nonce)
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    /// A UUID v4 string must be 36 characters and have '4' at index 14 (version marker).
    #[test]
    fn device_id_is_uuid_v4() {
        let id = uuid::Uuid::new_v4().to_string();
        assert_eq!(id.len(), 36, "UUID v4 must be 36 characters");
        assert_eq!(
            id.chars().nth(14),
            Some('4'),
            "UUID v4 must have '4' at position 14"
        );
    }

    /// Verify nonce one-time-use semantics at the Vec level (no Tauri State required).
    #[test]
    fn nonce_one_time_use() {
        let mut auth = AuthState::new();
        let nonce = "test-nonce-abc123".to_string();

        // Push a nonce directly.
        auth.pending_oauth_states.push(nonce.clone());
        assert!(
            auth.pending_oauth_states.contains(&nonce),
            "nonce must be present after push"
        );

        // First removal succeeds.
        let pos = auth.pending_oauth_states.iter().position(|n| n == &nonce);
        assert!(pos.is_some(), "nonce should be found on first lookup");
        auth.pending_oauth_states.remove(pos.unwrap());

        // Second lookup returns nothing.
        let pos2 = auth.pending_oauth_states.iter().position(|n| n == &nonce);
        assert!(pos2.is_none(), "nonce should be absent after consumption");
    }

    #[test]
    fn looks_like_jwt_accepts_real_shape() {
        assert!(looks_like_jwt("eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYmMifQ.signature1234"));
        assert!(!looks_like_jwt("no-dots"));
        assert!(!looks_like_jwt("only.two"));
        assert!(!looks_like_jwt("short.x.x"));
    }

    #[test]
    fn validate_url_shape_rejects_wrong_scheme() {
        assert_eq!(validate_url_shape("https://auth/callback?type=magiclink"), Err("wrong scheme"));
    }

    #[test]
    fn validate_url_shape_rejects_wrong_host() {
        assert_eq!(validate_url_shape("voice-tool://wrong/callback?type=magiclink"), Err("wrong host/path"));
    }

    #[test]
    fn validate_url_shape_rejects_wrong_path() {
        assert_eq!(validate_url_shape("voice-tool://auth/other?type=magiclink"), Err("wrong host/path"));
    }

    #[test]
    fn validate_url_shape_rejects_missing_type() {
        assert_eq!(validate_url_shape("voice-tool://auth/callback"), Err("missing type"));
    }

    #[test]
    fn validate_url_shape_rejects_unknown_type() {
        assert_eq!(validate_url_shape("voice-tool://auth/callback?type=hacker"), Err("type not whitelisted"));
    }

    #[test]
    fn validate_url_shape_rejects_malformed_jwt() {
        assert_eq!(
            validate_url_shape("voice-tool://auth/callback?type=magiclink&access_token=not-a-jwt"),
            Err("jwt field has wrong shape")
        );
    }

    #[test]
    fn validate_url_shape_accepts_valid_magiclink() {
        let result = validate_url_shape(
            "voice-tool://auth/callback?type=magiclink&access_token=eyJh.eyJh.signature1234&refresh_token=eyJh.eyJh.signature5678"
        );
        assert!(result.is_ok());
        let params = result.unwrap();
        assert_eq!(params.get("type").map(|s| s.as_str()), Some("magiclink"));
    }

    #[test]
    fn validate_url_shape_accepts_valid_oauth_with_state() {
        // OAuth state validation happens later via consume_nonce_from_state, not here.
        let result = validate_url_shape(
            "voice-tool://auth/callback?type=oauth&code=abc123&state=nonce-uuid"
        );
        assert!(result.is_ok());
    }
}
