// POC NOL-32 — Tauri command to open a LemonSqueezy checkout URL.
//
// Where it plugs in (v3):
//   1. Add to src-tauri/src/commands/mod.rs (or equivalent module).
//   2. Register the command in the Tauri builder: .invoke_handler(tauri::generate_handler![..., open_checkout])
//   3. The URL is built with a signed checkout link generated by LS dashboard or LS API.
//      For POC we accept the base checkout URL + user_id; custom_data travels via query string.
//
// Env the command relies on:
//   LEMON_SQUEEZY_CHECKOUT_URL  — e.g. https://<store>.lemonsqueezy.com/buy/<variant-uuid>
//
// NOTE: `tauri-plugin-opener` is already a dependency of this project (see src-tauri/Cargo.toml).

use serde::Serialize;
use tauri::AppHandle;
use tauri_plugin_opener::OpenerExt;

#[derive(Debug, Serialize)]
pub struct CheckoutOpenResult {
    pub opened_url: String,
}

#[derive(Debug, thiserror::Error, Serialize)]
pub enum CheckoutError {
    #[error("checkout url not configured (set LEMON_SQUEEZY_CHECKOUT_URL)")]
    MissingCheckoutUrl,
    #[error("user_id is required to attach custom_data for the webhook")]
    MissingUserId,
    #[error("failed to open external url: {0}")]
    OpenFailed(String),
}

/// Opens the LemonSqueezy checkout in the user's default browser.
///
/// `user_id` is the Supabase auth user id; it is passed as `checkout[custom][user_id]`
/// so the webhook can associate the resulting subscription with the right account.
/// `email` is optional — if provided, LS pre-fills the billing email.
#[tauri::command]
pub async fn open_checkout(
    app: AppHandle,
    user_id: String,
    email: Option<String>,
) -> Result<CheckoutOpenResult, CheckoutError> {
    if user_id.trim().is_empty() {
        return Err(CheckoutError::MissingUserId);
    }

    let base = std::env::var("LEMON_SQUEEZY_CHECKOUT_URL")
        .map_err(|_| CheckoutError::MissingCheckoutUrl)?;

    let mut url = url::Url::parse(&base).map_err(|e| CheckoutError::OpenFailed(e.to_string()))?;
    {
        let mut q = url.query_pairs_mut();
        q.append_pair("checkout[custom][user_id]", &user_id);
        if let Some(e) = email.as_deref() {
            q.append_pair("checkout[email]", e);
        }
        // Desktop UX: embed mode is disabled, LS opens in full browser tab.
        q.append_pair("embed", "0");
    }

    let final_url = url.to_string();
    app.opener()
        .open_url(&final_url, None::<&str>)
        .map_err(|e| CheckoutError::OpenFailed(e.to_string()))?;

    Ok(CheckoutOpenResult { opened_url: final_url })
}
